### ISSUE TITLE
Release to CPAN

### ISSUE THREAD

**Issue by reneeb** [jamadam/Mojolicious-Plugin-PlackMiddleware#2]
Hi,

can you release a new version to CPAN? Currently the module fails to install, but your repository seems to be clean...

Kind regards,
Renée

**Comment by jamadam** [comment]
Thanks for request!
I intend to release new version to CPAN as soon as possible.
It may takes some time to update compatibility tests in xt dirctory.

**Comment by jamadam** [comment]
I just uploaded new version to CPAN. Thanks for reminding me.
